name: Check dbt SQL formatting with SQLfluff

on:
  workflow_call:
    inputs:
      dbt_path:
        description: Path to folder with dbt project (without trailing slash)
        type: string
        required: true

jobs:
  check-sql-formatting:
    name: Check SQL formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.x"

      - name: Install sqlfluff
        run: pip install sqlfluff

      - name: Get changed files
        id: get_file_changes
        uses: tj-actions/changed-files@487675b843e203b5c9a92a07f1ed763d046d7283
        with:
          output: ' '

      - name: Get changed .sql files in ${{ inputs.dbt_path }} to lint
        id: get_files_to_lint
        shell: bash -l {0}
        run: |
          # Set the command in the $() brackets as an output to use in later steps
          echo "lintees=$(
          # Issue where grep regular expressions don't work as expected on the
          # Github Actions shell
          echo \
          $(echo ${{ steps.get_file_changes.outputs.all_changed_files }} |
          tr -s ' ' '\n' |
          grep -E '^${{ inputs.dbt_path }}/models.*[.]sql$' |
          tr -s '\n' ' ') |
          # Remove path prefix since we run sqlfluff in the dbt folder folder
          sed -e 's:${{ inputs.dbt_path }}/::g'
          )" >> $GITHUB_OUTPUT

      - name: Lint dbt models
        id: sqlfluff_json
        if: steps.get_files_to_lint.outputs.lintees != ''
        shell: bash -l {0}
        # Run sqlfluff and add oppetid/dbt to paths, so that Github annotations understands them
        run: |
          cd ${{ inputs.dbt_path }}
          sqlfluff lint --format github-annotation --annotation-level failure --nofail ${{ steps.get_files_to_lint.outputs.lintees }} --write-output annotations.json
          sed -i -e 's|"file": "|"file": "${{ inputs.dbt_path }}/|g' annotations.json

      - name: Annotate
        uses: yuzutech/annotations-action@3aa369f1f03cc794a39fe41608dfa004654974d0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "${{ inputs.dbt_path }}/annotations.json"
