name: Deploy dbt to BigQuery

on:
  workflow_call:
    inputs:
      dbt_path:
        description: Path to folder with dbt project (without trailing slash)
        type: string
        required: true
      dbt_args:
        description: Extra arguments to dbt, typically --target and --profile
        type: string
        required: true
      docs_bucket:
        description: Name of docs bucket (without gs://)
        type: string
        required: true
      dbt_model_filter:
        description: 'Filter ensure that only models that passes the filter is ran, format: filter1,filter2,etc. Filter1 is usually the project name'
        type: string
        required: false
        default: ''
      projects_config_path:
        description: Path to folder with projects.config.json
        type: string
        required: true
      environment:
        description: Name of environment (STM, ATM or PROD)
        type: string
        required: true
      service_account:
        description: Name of service account to run dbt with (default project-service-account)
        type: string
        required: false
        default: project-service-account

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dbt_path }}
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.x"

      - name: Setup gcloud
        uses: svvsaga/github-actions-public/setup-gcloud@v20.2.1
        with:
          environment: ${{ inputs.environment }}
          app_root: ${{ inputs.projects_config_path }}
          service_account: ${{ inputs.service_account }}

      - name: Copy old target files from Cloud Storage
        # In case we want to use previous state to determine which models to run
        run: |
          mkdir old-target
          gsutil cp gs://${{ inputs.docs_bucket }}/*.json old-target/

      - name: Install dependencies
        run: pip install dbt-bigquery==1.4

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run unit tests
        run: dbt test -m ${{ inputs.dbt_model_filter }},tag:unit-test ${{ inputs.dbt_args }}

      - name: dbt seed
        run: dbt seed -m ${{ inputs.dbt_model_filter }} ${{ inputs.dbt_args }}

      - name: dbt run
        run: dbt run -m ${{ inputs.dbt_model_filter }} ${{ inputs.dbt_args }}

      - name: dbt test
        run: dbt test -m ${{ inputs.dbt_model_filter }} ${{ inputs.dbt_args }}

      - name: Generate docs
        run: dbt docs generate ${{ inputs.dbt_args }}

      - name: Generate single HTML docs file
        uses: svvsaga/dbt-public/.github/actions/generate-single-doc-file@v1.0.2
        with:
          dbt-path: ${{ inputs.dbt_path }}

      - name: Copy HTML docs to Cloud Storage
        run: gsutil cp target/single_index.html gs://${{ inputs.docs_bucket }}/index.html

      - name: Copy JSON files to Cloud Storage
        run: gsutil cp target/*.json gs://${{ inputs.docs_bucket }}/