name: Deploy dbt to BigQuery

on:
  workflow_call:
    inputs:
      dbt_path:
        description: Path to folder with dbt project (without trailing slash)
        type: string
        required: true
      dbt_args:
        description: Extra arguments to dbt, typically --target and --profile
        type: string
        required: true
      credentials_file:
        description: File name for credentials, referred in target profile
        type: string
        required: true
      docs_bucket:
        description: Name of docs bucket (without gs://)
        type: string
        required: true
      dbt_model_filter:
        description: 'Filter ensure that only models that passes the filter is ran, format: filter1,filter2,etc. Filter1 is usually the project name'
        type: string
        required: false
        default: ''
    secrets:
      service_account_key:
        description: Base64-encoded JSON key for service account
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dbt_path }}
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Write credentials file
        run: 'echo "$KEYFILE" | base64 -d > ${{ inputs.credentials_file }}'
        shell: bash
        env:
          KEYFILE: ${{ secrets.service_account_key }}

      - name: Install dependencies
        run: pip install dbt-bigquery

      - name: Install dbt dependencies
        run: dbt deps --profiles-dir . ${{ inputs.dbt_args }}

      - name: Run unit tests
        run: dbt test -m ${{ inputs.dbt_model_filter }},tag:unit-test --profiles-dir . ${{ inputs.dbt_args }}

      - name: dbt seed
        run: dbt seed -m ${{ inputs.dbt_model_filter }} --profiles-dir . ${{ inputs.dbt_args }}

      - name: dbt run
        run: dbt run -m ${{ inputs.dbt_model_filter }} --profiles-dir . ${{ inputs.dbt_args }}

      - name: dbt test
        run: dbt test -m ${{ inputs.dbt_model_filter }} --profiles-dir . ${{ inputs.dbt_args }}

      - name: Generate docs
        run: dbt docs generate --profiles-dir . ${{ inputs.dbt_args }}

      - name: Setup Google Cloud SDK with service account key
        uses: svvsaga/github-actions-public/setup-gcloud-with-json-key@v8.0.1
        with:
          service_account_key: ${{ secrets.service_account_key }}

      - name: Generate single HTML docs file
        uses: svvsaga/dbt-public/.github/actions/generate-single-doc-file@v1.0.2
        with:
          dbt-path: ${{ inputs.dbt_path }}

      - name: Copy HTML docs to Cloud Storage
        run: gsutil cp target/single_index.html gs://${{ inputs.docs_bucket }}/index.html

      - name: Copy JSON files to Cloud Storage
        run: gsutil cp target/*.json gs://${{ inputs.docs_bucket }}/